# Generated by Django 3.2.7 on 2021-09-09 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('Name', models.CharField(max_length=150, verbose_name='')),
                ('Slug', models.SlugField(max_length=100, unique=True, verbose_name='')),
                ('IsSubCategory', models.BooleanField(default=False, verbose_name='زیر دسته بندی')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubCategory', to='product.category', verbose_name='')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی',
                'ordering': ('Name',),
            },
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, verbose_name='نام محصول')),
                ('Slug', models.SlugField(max_length=100, unique=True)),
                ('Images', models.ImageField(upload_to='Product/%y/%m/%d/%h/', verbose_name='عکس')),
                ('description', models.TextField(verbose_name='اطلاعات')),
                ('Price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('Available', models.BooleanField(default=True, verbose_name='دسترسی')),
                ('Store', models.PositiveIntegerField(verbose_name='تعداد محصول')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ManyToManyField(related_name='categories', to='product.Category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصول',
            },
        ),
    ]
