# Generated by Django 3.2.5 on 2021-08-08 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('Name', models.CharField(max_length=150)),
                ('Slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('Name',),
            },
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('Name', models.CharField(max_length=255)),
                ('Slug', models.SlugField(max_length=100, unique=True)),
                ('Images', models.ImageField(upload_to='Product/%y/%m/%d/%h')),
                ('description', models.TextField()),
                ('Price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('Available', models.BooleanField(default=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='product.category')),
            ],
            bases=('core.basemodel',),
        ),
    ]
