# Generated by Django 3.2.5 on 2021-08-21 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210809_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('Name',), 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصول'},
        ),
        migrations.AddField(
            model_name='product',
            name='Status',
            field=models.IntegerField(choices=[(0, 'تمام شده است'), (1, 'موجود است')], default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='IsSubCategory',
            field=models.BooleanField(default=False, verbose_name='زیر دسته بندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='Name',
            field=models.CharField(max_length=150, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='Slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubCategory', to='product.category', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='Available',
            field=models.BooleanField(default=True, verbose_name='دسترسی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.ManyToManyField(related_name='Product', to='product.Category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Images',
            field=models.ImageField(upload_to='Product/%y/%m/%d/%h/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.CharField(max_length=255, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='اطلاعات'),
        ),
    ]
