# Generated by Django 3.2.7 on 2021-09-09 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='ایمیل')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام ')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین بودن ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربر',
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.TextField(verbose_name='آدرس محل سکونت با کد بستی')),
                ('Mobile', models.CharField(max_length=11, verbose_name='تلفن همراه')),
                ('ProfileImage', models.ImageField(blank=True, null=True, upload_to='Profile/image', verbose_name='تصویر بروفایل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'حساب کاربری',
                'verbose_name_plural': 'حساب کاربری',
            },
        ),
    ]
