# Generated by Django 3.2.6 on 2021-08-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='ایمیل')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام ')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین بودن ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربر',
            },
        ),
    ]
